### ISSUE TITLE
Should we get a domain name?

### ISSUE THREAD

**Issue by terabyte128** [UW-HRC/uw-hrc.github.io#1]
From some cursory research, the following domains are available:

- huskyrunningclub.org
- uwhrc.org

I personally like uwhrc.org, because it's short and sweet, but we could also get both of them (they're only like $12 per year). I think having our own domain would make our website a lot more accessible, especially if we can get the correct tags going so it shows up on search engines. We could always just redirect everything to our current domain as well.

@rylio @akadouri opinions?

**Comment by akadouri** [comment]
I'm not sure if we need two, but having something easier to remember than students.washington.edu/uwrunner/ is probably a good idea. The club can also probably pay for it.

**Comment by terabyte128** [comment]
Yeah, I figured ;)

**Comment by rylio** [comment]
Yeah, I think we should definitely our own domain, preferably something short.

**Comment by terabyte128** [comment]
@akadouri suggested dawgs.run, which I really like.

**Comment by rylio** [comment]
Same, I like using the TLDs so it actually says something.

**Comment by terabyte128** [comment]
woohoo go [dawgs.run](http://dawgs.run)
